spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cklm?user=root&password=admin&useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false
    data-username: root
    data-password: admin
    driver-class-name: com.mysql.jdbc.Driver

    # 配置监控统计拦截的filters,去掉后监控界面sql将无法统计,'wall'用于防火墙
    filters: stat,wall,log4j

    tomcat:
      #最大活跃数
      max-active: 20
      #初始化数量
      initial-size: 1
      #最大连接等待超时时间
      max-wait: 60000
      # 打开PSCache,并且指定每个连接PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      #通过connection-properties属性打开mergeSql功能,慢SQL记录
      connection-properties: druid.stat.mergeSql = true;druid.stat.slowSqlMillis = 5000
      minldle : 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery : select 1 from dual
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false

  jpa:
    database: mysql
    show-sql: true
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

