spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cklm?user=root&password=admin&useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false
    data-username: root
    data-password: admin
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

